server:
  port: 0

spring:
  application:
    name: product-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  kafka:
    consumer:
      group-id: product-service
      topic:
        user-topic: USER_TOPIC
        order-topic: ORDER_TOPIC
    producer:
      properties:
        reconnect-backoff-ms: 1000
        reconnect-backoff-max-ms: 10000
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: embedded
    properties:
      org:quartz:
        scheduler:
          instanceName: PromotionScheduler
          instanceId: AUTO
file:
  service:
    name: file-service
    url: ${FILE_SERVICE_URL:http://localhost:6969}

outbox:
  cron-job-rate-ms: ${OUTBOX_CRON_JOB_RATE_MS:5000}

cache:
  warm-up:
    enable: true
    batch-size: 20000
  product:
    modified-time:
      ttl: 15 # seconds
async:
  core-pool-size: 10
  max-pool-size: 20
  queue-capacity: 100
genai:
  generation:
    model: ${GENAI_GENERATION_MODEL:gemini-2.5-flash}
  api:
    key: ${GENAI_API_KEY}
  embedding:
    model: ${GENAI_EMBEDDING_MODEL:text-embedding-004}

