server:
  port: ${SERVER_PORT:8084}
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always