server:
  port: ${SERVER_PORT:8081}
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
spring:
  application:
    name: identity-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
file:
  upload:
    max-size: ${FILE_UPLOAD_MAX_SIZE:10}
order:
  timeout:
    order-cancel-minutes: ${ORDER_CANCEL_TIMEOUT_MINUTES:15}