server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/glmj10/config-repo.git
          search-paths:
            - "/*"
          default-label: main
          username: ${GITHUB_USERNAME:glmj10}
          password: ${GITHUB_TOKEN}
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost